python Main.py -model STPM -loss_function MKD -Class bottle
python Main.py -model STPM -loss_function MKD -Class cable
python Main.py -model STPM -loss_function MKD -Class capsule
python Main.py -model STPM -loss_function MKD -Class carpet
python Main.py -model STPM -loss_function MKD -Class grid
python Main.py -model STPM -loss_function MKD -Class hazelnut
python Main.py -model STPM -loss_function MKD -Class leather
python Main.py -model STPM -loss_function MKD -Class metal_nut
python Main.py -model STPM -loss_function MKD -Class pill
python Main.py -model STPM -loss_function MKD -Class screw
python Main.py -model STPM -loss_function MKD -Class tile
python Main.py -model STPM -loss_function MKD -Class toothbrush
python Main.py -model STPM -loss_function MKD -Class transistor
python Main.py -model STPM -loss_function MKD -Class wood
python Main.py -model STPM -loss_function MKD -Class zipper

python Main.py -model MKD -loss_function STPM -Class bottle
python Main.py -model MKD -loss_function STPM -Class cable
python Main.py -model MKD -loss_function STPM -Class capsule
python Main.py -model MKD -loss_function STPM -Class carpet
python Main.py -model MKD -loss_function STPM -Class grid
python Main.py -model MKD -loss_function STPM -Class hazelnut
python Main.py -model MKD -loss_function STPM -Class leather
python Main.py -model MKD -loss_function STPM -Class metal_nut
python Main.py -model MKD -loss_function STPM -Class pill
python Main.py -model MKD -loss_function STPM -Class screw
python Main.py -model MKD -loss_function STPM -Class tile
python Main.py -model MKD -loss_function STPM -Class toothbrush
python Main.py -model MKD -loss_function STPM -Class transistor
python Main.py -model MKD -loss_function STPM -Class wood
python Main.py -model MKD -loss_function STPM -Class zipper

python Main.py -model MKD -loss_function MKD -Class bottle
python Main.py -model MKD -loss_function MKD -Class cable
python Main.py -model MKD -loss_function MKD -Class capsule
python Main.py -model MKD -loss_function MKD -Class carpet
python Main.py -model MKD -loss_function MKD -Class grid
python Main.py -model MKD -loss_function MKD -Class hazelnut
python Main.py -model MKD -loss_function MKD -Class leather
python Main.py -model MKD -loss_function MKD -Class metal_nut
python Main.py -model MKD -loss_function MKD -Class pill
python Main.py -model MKD -loss_function MKD -Class screw
python Main.py -model MKD -loss_function MKD -Class tile
python Main.py -model MKD -loss_function MKD -Class toothbrush
python Main.py -model MKD -loss_function MKD -Class transistor
python Main.py -model MKD -loss_function MKD -Class wood
python Main.py -model MKD -loss_function MKD -Class zipper
