python STPM.py -Class bottle
python STPM.py -Class cable
python STPM.py -Class capsule
python STPM.py -Class carpet
python STPM.py -Class grid
python STPM.py -Class hazelnut
python STPM.py -Class leather
python STPM.py -Class metal_nut
python STPM.py -Class pill
python STPM.py -Class screw
python STPM.py -Class tile
python STPM.py -Class toothbrush
python STPM.py -Class transistor
python STPM.py -Class wood
python STPM.py -Class zipper